apiserver:
  server: http://95.164.68.168:8080

fixtures: fixtures.json

email: ntelepenin@cloudlinux.com

# "Authorization: Bearer $TOKEN_VALUE"

# token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTF3eTF0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5MDRjYzRiZS0xOTBjLTExZTYtYmU5OS0wMjAwNWZhNDQ0YTgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.n3ZK57aXUjM2IlJPnfcOP-n6pw8TIyzyXsfws8BtFnPLh9SGq4DfbNFPQT0f4YhyrC6iXH3-7kVOHNG3v7hDD7rwOSfdZqnzpm0YUfH1lrX_kfdKvoFRNH5hXtp7PHzVgDq_dQy30ZLy1xIaRdjKZ0O_9fuaw76MrgKytrQ5vTQSwx4rZ4QvQn8A70IQs38pkBH0MAHLDArwHnqd5wCDSLf9JX3w91hPwcKPPXqATqSKbxY0-kQfNlRBScGDQNyDuEM7vtNb6BgZWZZq17Wk6-XOJSCMKei2q2qHOie9xO5RmkrpS3IAMTfkiSJ1YKW8jaNIwFSHPm8STuDa3rGKHg