apiVersion: v1
kind: ReplicationController
metadata:
  name: certbot-rc
  labels:
    app: certbot
spec:
  replicas: 1
  selector:
    app: certbot
  template:
    metadata:
      labels:
        app: certbot
    spec:
      containers:
      - image: prefer/certbot:0.36
        imagePullPolicy: Always
        name: certbot
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/letsencrypt/
          name: certbot-storage
      volumes:
      - name: certbot-storage
        emptyDir: {}