apiVersion: v1
kind: Service
metadata:
  name: certbot-svc
  labels:
    app: certbot
    type: letsencrypt
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: test-server
  selector:
    app: certbot
    type: letsencrypt